### ISSUE TITLE
Can't connect to server / Games dont start

### ISSUE THREAD

**Issue by kevinscheithauer** [dead/moonlight-openelec-rpi2#1]
Hi there,
when I sucessfully pair my computer and try to start one of the games that are listed (the list seems to be correct as far as I can tell) the raspberry pi 2 just restarts. I tried changing resolution and fps and it didnt work

**Comment by dead** [comment]
The raspberry restart or just the Interface?
Can you upload the `Userdata\addon_data\script.moonlight\service.log` file? Or just open it and see if there is any visible error.

**Comment by kevinscheithauer** [comment]
I actually had it work once now but after retrying it restarted the interface again.
Also it seems that pairing is a bit difficult cause the window with the code opens fairly late/only when you mash pair over and over and then I try one code it displays over and over on my PC.
[service.txt](https://github.com/dead/moonlight-openelec-rpi2/files/133980/service.txt)

**Comment by dead** [comment]
Try using the newest release (1.0.3), fixed the paring issue. Some times I get some random "Can't connect to server", try restarting GeForce Experience.

**Comment by kevinscheithauer** [comment]
The new version definitely improved the pairing situation but I don't seem to be able to fix the connection issue. Do you mean restarting the services? I tried that and it didn't change anything. The Android version of Moonlight works btw. so it has probably to do with something in the embedded version. Do you know what that alsa error is about?

**Comment by dead** [comment]
> The Alsa errors are sometimes normal. The GFE will stop sending audio packets if there's no audio being played from the PC. This can cause underruns that lead to those messages in the logs.
> From: https://github.com/irtimmer/moonlight-embedded/issues/175

**Comment by dead** [comment]
irtimmer/moonlight-embedded#272

**Comment by dead** [comment]
It is not a addon issue so I'm gonna close this.

**Comment by dead** [comment]
So in the end it was a problem in the addon. Fixed it.
Thank you.

**Comment by kevinscheithauer** [comment]
Definitely works now. Glad I could help.
