### ISSUE TITLE
Addon does not have the correct structure

### ISSUE THREAD

**Issue by Bite-A-Rock** [dead/moonlight-openelec-rpi2#10]
Hello,
  Trying to install v1.0.8 and getting the following error in Kodi: Addon does not have the correct structure

Downloaded latest release from the releases page.

HW: Raspberry Pi v2
OS: Openelec v6.0.3

Thanks!

**Comment by dead** [comment]
Try the "[script.moonlight.zip](https://github.com/dead/moonlight-openelec-rpi2/releases/download/v1.0.8/script.moonlight.zip)" It should work :smile:

**Comment by Bite-A-Rock** [comment]
Hi, thanks for the reply.  That is the one I tried. :-/

**Comment by dead** [comment]
Oh, that's weird. Try unzip it and zipping the script.moonlight folder again.

**Comment by Bite-A-Rock** [comment]
Well, inside the script.moonlight.zip is the folder script.moonlight containing the various files.

Should the various files be inside the zip directly or inside the script.moonlight folder inside the zip?

**Comment by dead** [comment]
The zip should contain the folder with the files inside it.

**Comment by Bite-A-Rock** [comment]
Well, I re-zipped with the folder inside the zip file.  Kodi still claims a structure problem.  I will try to research what the structure is supposed to look like and go from there.  Thanks for you help.

**Comment by Bite-A-Rock** [comment]
Got it to install. Yea!  Paring problem.  I will open a new ticket.

Thank you for your help.  I am not sure what finally made it work, I just keep zipping and unzipping. Then it finally went.

Thanks!
