### ISSUE TITLE
Dualshock mapping

### ISSUE THREAD

**Issue by screwfaze** [dead/moonlight-openelec-rpi2#11]
Hi,

Thanks for the amazing app, small issue with dualshock3 controller the left analog stick is mapped wrong how can I fix ?

Thanks

**Comment by rapidreporter** [comment]
You can map your own device. It's simple :)
ssh into your device and type:
moonlight map <filename> 
example:
monnlight map mygamepad.conf

Then the commandline tells you what button you should push on your joypad.

copy mygamepad.conf to 
~/.kodi/addons/script.moonlight/bin/mappings

then nano ~/.kodi/addons/script.moonlight/resources/settings.xml

Edit the part with the setting id. should look like thins then if you took the name of my example

<setting id="MOON_MAPPING" type="select" label="Control Mapping"
values="default|dualshock3|dualshock4|rumblepad2|xbox360|mygamepad"
default="mygamepad" />

save the file:
Open moonlight configuration on openelec (rightclick on the addon there where you set the ip and this stuff)
Now you see "mygamepad" on the controller section.

select it. Your done :)

You can always do moonlight map <filename> again if something go wrong.

Hope it helps :)

**Comment by screwfaze** [comment]
Hi,

Thanks that worked. Small problem though when using the d-pad when I press once it keeps moving like I am holding down the button. This is in all directions and I have checked connecting directly to my computer there is no problem. Is this something you can help with?

Thanks

**Comment by rapidreporter** [comment]
Great that the major problem is solved. With the smaller problem. Maybe you press the buttons wrong? Sounds stupid I know. :p First time I made my configuration I messed up with left and right "head"... Maybe you did it wrong there?

**Comment by dead** [comment]
Take a look at this: https://github.com/irtimmer/moonlight-embedded/issues/264#issuecomment-201403699

**Comment by dead** [comment]
https://github.com/dead/moonlight-openelec-rpi2/issues/13#issuecomment-208370447
