### ISSUE TITLE
Latest GFE 2.11.2.46 breaks Addon

### ISSUE THREAD

**Issue by Porhoken** [dead/moonlight-openelec-rpi2#12]
The latest version of GFE is not working with the Addon. There have been changes to the pairing process. Moonlight sources have already been updated. https://github.com/irtimmer/moonlight-embedded/commit/7c4768593c67461f13f871df7b0458c567e5be76
Unfortunately, I don't know how to bring these changes to your addon.
Thanks for your great work. :)
Best,
Ken

**Comment by dead** [comment]
I'm going to update it when it is released. It's not complete yet.
Thanks :smile:

**Comment by Porhoken** [comment]
Ah, okay, didn't see that. Thought it was out already as the android client updated today. Nevermind and thx again. :)

**Comment by MedicInMirrorshades** [comment]
Thanks for the update- was going to report that myself. So when it is out, do we have to reinstall the script or is there an easy way to update it through the add-on? Thanks for all you do!

**Comment by dead** [comment]
You will have to download and update it by yourself :cry: But I have plans to create a repository to make this easier.

**Comment by MedicInMirrorshades** [comment]
That would be awesome. I can handle a little bit of work for now though:-)

**Comment by dead** [comment]
https://github.com/dead/moonlight-openelec-rpi2/commit/1ec7269213993c11b713d39105eb80c96710748b closes this. :smile:
