### ISSUE TITLE
Opening addon gives an error in Kodi

### ISSUE THREAD

**Issue by sevenpoundowl** [dead/moonlight-openelec-rpi2#13]
I'm running OpenELEC-RPi2.arm-6.95.1 and installed the addon from the zip file.

From the log -

 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: libmoonlight-common.so.0: cannot open shared object file: No such file or directory
                                            Traceback (most recent call last):
 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: libmoonlight-common.so.0: cannot open shared object file: No such file or directory
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 78, in <module>
                                                index()
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 25, in index
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")
                                              File "/storage/.kodi/addons/script.moonlight/resources/moonlight.py", line 36, in **init**
                                                self.gslib = ctypes.cdll.LoadLibrary(os.path.join(libpath, "libgamestream.so.0"))
                                              File "/home/stephan/projects/openelec-7.0/build.OpenELEC-RPi2.arm-6.95.1/Python-2.7.11/.install_pkg/usr/lib/python2.7/ctypes/**init**.py", line 443, in LoadLibrary
                                              File "/home/stephan/projects/openelec-7.0/build.OpenELEC-RPi2.arm-6.95.1/Python-2.7.11/.install_pkg/usr/lib/python2.7/ctypes/**init**.py", line 365, in **init**
                                            OSError: libmoonlight-common.so.0: cannot open shared object file: No such file or directory

**Comment by dead** [comment]
Try putting this on /storage/.kodi/script.moonlight/lib folder.
[libssl.so.32](https://github.com/dead/moonlight-openelec-rpi2/files/177032/libssl.so.32.zip) and [libcrypto.so.32](https://github.com/dead/moonlight-openelec-rpi2/files/178992/libcrypto.so.32.zip)

And check if there is a libmoonlight-common.so.0 in there.

**Comment by Serg86** [comment]
I still have this problem on Openelec 6.0.3.

The libs are all there. I can pair and start moonlight manually via SSH, but starting the addon from Kodi results in an error and the same log entry.

**Comment by dead** [comment]
Can you test this? [script.moonlight.zip](https://github.com/dead/moonlight-openelec-rpi2/files/212091/script.moonlight.zip)
Thanks!

**Comment by Serg86** [comment]
`13:52:13 38076.996094 T:1501557824  NOTICE: Thread JobWorker start, auto delete: true
13:52:13 38077.031250 T:1477440576  NOTICE: Thread BackgroundLoader start, auto delete: false
13:52:13 38077.035156 T:1449129024  NOTICE: Thread JobWorker start, auto delete: true
13:52:16 38079.570312 T:1477440576  NOTICE: Previous line repeats 2 times.
13:52:16 38079.570312 T:1477440576  NOTICE: Thread LanguageInvoker start, auto delete: false
13:52:16 38079.707031 T:1477440576  NOTICE: -->Python Interpreter Initialized<--
13:52:16 38080.015625 T:1477440576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: /storage/lib/libcurl.so.4: version 'CURL_OPENSSL_4' not found (required by /storage/.kodi/addons/script.moonlight/lib/libgamestream.so.0)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 78, in <module>
                                                index()
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 25, in index
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")
                                              File "/storage/.kodi/addons/script.moonlight/resources/moonlight.py", line 37, in __init__
                                                self.gslib = ctypes.cdll.LoadLibrary(os.path.join(libpath, "libgamestream.so.0"))
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-RPi2.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-RPi2.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
                                            OSError: /storage/lib/libcurl.so.4: version 'CURL_OPENSSL_4' not found (required by /storage/.kodi/addons/script.moonlight/lib/libgamestream.so.0)
                                            -->End of Python script error report<--
13:52:16 38080.207031 T:1967980544   ERROR: GetDirectory - Error getting plugin://script.moonlight/
13:52:16 38080.207031 T:1967980544   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.moonlight/) failed
13:52:16 38080.230469 T:1477440576  NOTICE: Thread BackgroundLoader start, auto delete: false
`

This is the new error message. libcurl.so.4 exists in /storage/lib. I tried copying it to the addons lib folder, no change.

NOTE: I changed some of the characters in the output because they are the same ones used to mark code snippets, to make the output appear more consistent.

**Comment by dead** [comment]
Why its using /storage/lib and not just /lib ? libcurl should be the one from /usr/lib

**Comment by Serg86** [comment]
/storage/lib is the first path in LD_LIBRARY_PATH. I tried manually changing it, but it still wants /storage/lib/libcurl.so.4.

Edit: I deleted .kodi/addons/script-moonlight and .kodi/userdata/addon_data/script.moonlight to reinstall it from scratch, changed LD_LIBRARY_PATH to not contain /storage/lib and reinstalled, same thing.

**Comment by dead** [comment]
Why do you have a /storage/lib? Custom addon?

**Comment by Serg86** [comment]
Nope, I actually don't know. Perhaps another addon made it. My LD_LIBRARY_PATH is quite long.

**Comment by dead** [comment]
This should fix your problem: [script.moonlight.zip](https://github.com/dead/moonlight-openelec-rpi2/files/212927/script.moonlight.zip)

**Comment by Serg86** [comment]
It says the addon does not have the correct structure.

**Comment by dead** [comment]
https://github.com/dead/moonlight-openelec-rpi2/issues/10#issuecomment-199577313

**Comment by Serg86** [comment]
I've tried rezipping the contents in Windows 7, copied them over, same thing. I tried the same thing in my Ubuntu 16.04 VM, still the same thing.

Anyway, I installed an older .zip and simply replaced the files manually, no change I'm afraid. kodi.log still maintains /storage/lib is where libcurl.so.4 needs to be, which it is.

**Comment by dead** [comment]
I put `os.environ['LD_LIBRARY_PATH'] = "/usr/lib:/lib:" + addon.getAddonInfo("path") + "/lib"`in the addon.py so it should not look in /storage/lib folder anymore. There is a libcurl.so.4 in /usr/lib ?

**Comment by Serg86** [comment]
Yes.

Edit: I just tried the crowbar method, I renamed the libcurl.so.4 file in /storage/lib to libcurl.so.4_backup and tried to start moonlight again, no change. kodi.log still produces the same output.

Edit2: Copying /usr/lib/libcurl.so.4 to /storage/lib also makes no difference.

**Comment by dead** [comment]
Try copying /usr/lib/libcurl.so.4 to /storage/.kodi/script.moonlight/lib...
I have no idea why do you have two libcurl, I would suggest trying in clean install of openelec or try to find out what addon is using the /storage/lib and remove it.
There isn't much I can do if the default libcurl is being replaced. Sorry.

**Comment by Serg86** [comment]
Thank you for your time. I managed to solve it by renaming /storage/lib to lib_backup, removing it from LD_LIBRARY_PATH and rebooting the Pi. No idea what addon will stop working, so far, all the ones I use a lot still work.

Also, DS3 seems to have inverted Y axis on the left stick, Y axis on the right stick isn't working at all. Haven't tested the other buttons yet.

Edit: This dualshock3.conf works perfectly for me with an original PS3 DualShock 3 controller:

abs_x = 0
abs_y = 1
abs_z = 48
abs_rx = 2
abs_ry = 5
abs_rz = 49
abs_deadzone = 0
abs_dpad_x = -1
abs_dpad_y = -1
reverse_x = false
reverse_y = true
reverse_rx = false
reverse_ry = true
reverse_dpad_x = false
reverse_dpad_y = false
btn_west = 303
btn_south = 302
btn_north = 300
btn_east = 301
btn_select = 288
btn_start = 291
btn_mode = 304
btn_thumbl = 289
btn_thumbr = 290
btn_tl = 298
btn_tr = 299
btn_tl2 = 296
btn_tr2 = 297
btn_dpad_up = 292
btn_dpad_down = 294
btn_dpad_left = 295
btn_dpad_right = 293

**Comment by dead** [comment]
Did you change in the addon settings to use the dualshock3 mapping?
If this does not work try creating a new map file using `moonlight map /storage/.kodi/addons/script.moonlight/bin/mappings/dualshock3.conf`
And please share the mapping, maybe it will work for other people too :smile:

**Comment by Serg86** [comment]
I did change it. I created a new mapping file and just modified the wrong values in the old file via ssh. I tested all buttons in The Witcher 3, everything is working perfectly. I posted it in the edit above.

**Comment by Serg86** [comment]
Found the culprit! [Gamestarter](https://github.com/bite-your-idols/gamestarter-openelec) installs an addon that downgrades a few libs, libcurl even being the one specifically mentioned in the readme.

**Comment by dead** [comment]
Can you post here the modified mapping for dualshock 3? Thanks!

**Comment by hendrikras** [comment]
is there a working zip file for this issue?

**Comment by dead** [comment]
@snkhubcom what is your problem?
