### ISSUE TITLE
Failed connect to server

### ISSUE THREAD

**Issue by ArturKaul** [dead/moonlight-openelec-rpi2#15]
Hi,
I'm running OpenELEC-RPi2.arm-6.0.3 and installed the addon from the zip file "script.moonlight v1.0.10".
Error
Failed connect to server (192.168.178.55)
I have GFE 2.11.2.66
Please help
Thank you

**Comment by rapidreporter** [comment]
Please provide the following info: logs from Userdata\addon_data\script.moonlight\service.log

thx ;)

**Comment by ArturKaul** [comment]
service.log does not exist :(

**Comment by ArturKaul** [comment]
with GFE 2.11.2.46 is all ok
ist GFE 2.11.2.66 dont support?

**Comment by rapidreporter** [comment]
you could try to do it manually, to get closer to the error.
Pls. connect to your pi over ssh
on the terminal enter

```
         moonlight stream -app Steam 192.168.XXX.YYY
```

you propably need to pair again with your pc at this moment

Pls write down the output from your terminal after trying the command.
Maybe we then could see where it crashes.

I'm running on GFE 2.11.2.67 and it's runnig without problems.

;)

**Comment by ArturKaul** [comment]
Moonlight Embedded 2.2.0 (EMBEDDED;PI)
Connect to 192.168.178.55...
Can't connect to server 192.168.178.55

**Comment by rapidreporter** [comment]
Ok did you ever had a connection to your server with any other device?
I-Phone or Android?
Could it be that your PC is behind a firewall or other routers which do not forward things for moonlight?
TCP-Ports that should be open: NVIDIA moonlight 35043, 47984, 47989, 47995, 47996, 48010
UDP-Pors that should be open: NVIDIA moonlight 47998, 47999, 48000, 48010,

**Comment by ArturKaul** [comment]
Firewall is off, Ports are open.
The same Problem ist with Android too. 
In Experience Preference is no GameStream Tab.

**Comment by rapidreporter** [comment]
Ok. First question.
- What graphic card are you using?
  Second:
- If it is a compatible nvidia graphic card, then did you update the drivers?

you can check both by visiting this website: http://www.geforce.com/geforce-experience/system-requirements

If it will not work with your android phone, it will not work with moonlight too. 
The problem is not on the addon side it's on the pc side. 
Please check System Requirements.

**Comment by ArturKaul** [comment]
Thank you,
I realized that it was not in the moonlight. I can not find anything on the internet about this. When I updated to the latest version of your moonlight, it all turned out. That's just for some reason, is now on the PC tab gamestream disappeared and I can not do it
From Moonlight Quick Setup Instructions:
Start up GeForce Experience on the server and navigate to the Preferences tab. Then choose the SHIELD option. Make sure the Allow this PC to stream games to SHIELD devices checkbox is checked. To set up streaming from the Internet, see Streaming over the Internet later on in the guide.

I have
GTX 970
Driver ist uptodate.

If I reinstall the Experience Tab is, after rebooting disappears.

**Comment by ArturKaul** [comment]
O dont have this
http://www.howtogeek.com/wp-content/uploads/2016/02/ximg_56b27c60d995c.png.pagespeed.gp+jp+jw+pj+js+rj+rp+rw+ri+cp+md.ic.dPXIjUQTYc.png

**Comment by rapidreporter** [comment]
Confused...
- GTX 970 is ok.
- maybe reinstalling Geforce Experience help.
- By the way I think you need to create a account and log in into gforce Experience. Could not look at it at the moment. Typing from another pc.

If this all is not helping. Pls search at the nvidia Forum :) 

By the way is not my plugin is the plugin form dead :)

**Comment by ijontek** [comment]
@ArturKaul, stupid question, but I managed to make this mistake way to often. Have you booted Nvidia GeForce Experience app before trying to pair with moonlight device?

**Comment by rapidreporter** [comment]
Did it work now, or do you give up?
If it works pls. tell others what you did. Thx
