### ISSUE TITLE
addon does not have the required structure

### ISSUE THREAD

**Issue by hansiiiii** [dead/moonlight-openelec-rpi2#17]
Hello,

if I go to Settings > Addons > Install from zip file, I get the error message "addon does not have the required structure" (free translate from the german error message).
I use a Raspberry Pi 3 with OpenElec 6.03. What can I do or what's the problem here?

Thanks for your work and regards!
Hansi

**Comment by dead** [comment]
I'm not entirely sure why this happen, try this: https://github.com/dead/moonlight-openelec-rpi2/issues/10#issuecomment-199577313

**Comment by hansiiiii** [comment]
Ok, I did it 10 times with different folder-structures - without success.
BUT: I've created the zip files with WinRAR. NOW I used the windows owned zipper and tadaaa - the installation works now.  :-S

Thank you! :)

**Comment by willhowlett** [comment]
I had this happen when I downloaded the main repo zip file, but downloading the zip from the actual releases page worked fine
