### ISSUE TITLE
Game didn't start; "respring" to openelec

### ISSUE THREAD

**Issue by rapidreporter** [dead/moonlight-openelec-rpi2#2]
I'm new in GitHub so let's start with saying Hello and thx for your work.

Unfortunately, I tryed since 4 days to get moonlight running on my openelec and it is not going to start.

Let's start with explaining what did already worked for me:

other devices:
- I-Pod touch, start streaming, works..
- on my other SD with raspbian I installed moonlight and there it starts

openelce:
- pairing; works
- seeing library of games; works

now to the Part that give me headache:
- as soon as I try to start any game or steam or desktop tv gets black "respring" and start kodi again
  (not really a reboot)
- dobble checked my settings, still the same
- tried it since version 1.0.2 and I am actually on v 1.0.4
- also followed the hint with gfe 2.7.4.10 and downgraded to this version. Still the same.
  
  service.log says..

Connect to stream...
-packetsize 1024 -bitrate 10000 -720 -30fps -forcehw -remote -mapping "/storage$
Can't connect to server stream
Moonlight Embedded 2.1.3 (EMBEDDED;PI)
Connect to stream...

Ok thougt it might be really an IP-Problem, now thats what I tried...
- ssh to openelec and ping from there to host. All fine, had a replie
- then I tried to start moonlight manually from ssh by typing  
  moonlight stream -app Steam 192.168.2.10
- needed to pair again ok 
  moonlight pair 192.168.2.10, done
- again moonlight steam -app Steam 192.168.2.10
  Steam started on my PC but nothing on openelec
- retried it again from openelec, and log still telling me "Cannot connect to Server stream"

I'm a little bit stucked right now and hope maybe someone have a working solution.

almost forget to say it is a rpi2 with openelec version 6.0.1 (kernel:Linux 4.1.16)

Thx and greets

**Comment by dead** [comment]
To run moonlight-embedded in Openelec you need first stop the kodi service `systemctl stop kodi` and then run it. This is what this addon does. (that's why you see screen going black and then kodi starting).

Looking at the log you posted

> Connect to stream...
> -packetsize 1024 -bitrate 10000 -720 -30fps -forcehw -remote -mapping "/storage$
> Can't connect to server stream

It seems that the service.sh is putting the arguments to moonlight in the wrong order. Going to fix it now.

**Comment by dead** [comment]
Thank you :)

**Comment by rapidreporter** [comment]
You made my Day :) 
Finally works +1: 
thx
