### ISSUE TITLE
Cannot use d-pad with X360 controller

### ISSUE THREAD

**Issue by ijontek** [dead/moonlight-openelec-rpi2#22]
Hey,

I have some trouble with setting up the Xbox 360 wireless controller with your addon. First, I noticed that 'X' button is switched with 'Y' button, but I discovered that I was on 'default' controller configuration. Therefore, I tried 'x360' config, that you provided in settings. However, when I booted Steam or Dark Souls, or any other app that uses d-pad for navigation, I could not get it to work. I tried replacing the xbox controller configuration, with different mappings I found on the Internet, to no avail (sorry I do not remember, which one I tried now). 

D-pad i absolutely unresponsive, as though they are not mapped at all.

Have you ever seen this issue?

Cheers,
Rad

**Comment by dead** [comment]
You can map your own via command line using `moonlight map newmapping.conf`

**Comment by ijontek** [comment]
Actually the problem fixed itself, when I finally updated Openelec from
5.0.8 to 6.0.3. So, there is that. 😀
7 maj 2016 17:36 "Gustavo" notifications@github.com napisał(a):
