### ISSUE TITLE
Ignoring overscan

### ISSUE THREAD

**Issue by MrKrabat** [dead/moonlight-openelec-rpi2#25]
Hello,

this addon ignores the overscan settings, which means it does not fit the screen.

Overscan is a feature to adjust the video output to you monitor, but in the most cases this causes that the video is smaller or bigger than your monitor. (just why?!)
settings > system > video output > video calibration...

In my case the video is bigger than my 1920x1080p TV. I have adjusted the settings to fit the screen size but Moonlight ignores it. This means there are some centimeters out of the visible range.

LibreELEC 7.0.2
Moonlight 7.0.101

**Comment by monsieurpouet** [comment]
Maybe, you need ajust jour screen by kodi (in the system settings). 
Because you can do that. So you'll ne able to adjust the position of image. 

Le 6 août 2016 20:58:28 GMT+02:00, MrKrabat notifications@github.com a écrit :

> Hello,
> 
> this addon ignores the overscan settings, which means it does not fit
> the screen.
> 
> Overscan is a feature to adjust the video output to you monitor, but in
> the most cases this causes that the video is smaller or bigger than
> your monitor. (just why?!)
> settings > system > video output > video calibration...
> 
> In my case the video is bigger than my 1920x1080p TV. I have adjusted
> the settings to fit the screen size but Moonlight ignores it. This
> means there are some centimeters out of the visible range.
> 
> LibreELEC 7.0.2
> Moonlight 7.0.101
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dead/moonlight-openelec-rpi2/issues/25

##

**Comment by dead** [comment]
https://github.com/irtimmer/moonlight-embedded/issues/161

**Comment by MrKrabat** [comment]
thanks!

I changed a setting on my TV and now it is working without dealing with overscan.

> Note: the best solution is to disable overscan on the TV/monitor. Check the display menu options (it may be called "just scan", "screen fit", "HD size", "full pixel", "unscaled", "dot by dot", "native" or "1:1"), then use the disable_overscan=1 option.

Source: http://elinux.org/R-Pi_Troubleshooting#Big_black_borders_around_small_image_on_HD_monitors
