### ISSUE TITLE
Duplicate PC screen

### ISSUE THREAD

**Issue by monsieurpouet** [dead/moonlight-openelec-rpi2#26]
Hi !

So, we can use our games on own TV with moonlight.
But, I'am a guitar player and I would like put my tab on my screen since my PC (windows). Can I ?

So, I would like deport my PC screen to Kodi without any cable (like when I'am playing to my games).

Do you see what I say ?
It's possible ?

**Comment by dead** [comment]
Add `mstsc.exe` in the GeForce Experience -> Settings -> Shield -> GameStream -> + and you will be able to stream the entire desktop.
