### ISSUE TITLE
Odroid

### ISSUE THREAD

**Issue by kmxak** [dead/moonlight-openelec-rpi2#27]
Hey is it possible to get the plugin work with odroid c2?
I only getting Bluescreen or crashes wile using moonlight.

**Comment by dead** [comment]
Are you using libreelec or openelec?

**Comment by kmxak** [comment]
libreelec

**Comment by Munkenmo** [comment]
relevant info can be found on [this Odroid Forums thread.](http://forum.odroid.com/viewtopic.php?f=144&t=22999)

particularly:

> Running it from a SSH session yields the following:
> 
> LibreELEC:~/.kodi/addons/script.moonlight/bin # moonlight list
> Moonlight Embedded 2.2.0 (EMBEDDED;PULSE;CEC;AML)
> Platform 'default' not found
> 
> LibreELEC:~/.kodi/addons/script.moonlight/bin # moonlight --platform aml list
> Moonlight Embedded 2.2.0 (EMBEDDED;PULSE;CEC;AML)
> Platform 'aml' not found
> 
> This means the plugin is not compiled properly with Amlogic support.

**Comment by crazyquark** [comment]
any help on this?
can we compile moonlight on device?
A moonlight-embedded port for Odroid C2 does exist:
http://magazine.odroid.com/wp-content/uploads/ODROID-Magazine-201610.pdf#page=22

**Comment by dead** [comment]
I think this was already fixed, I bought an Odroid C2 so I'm going to check this 😄
