### ISSUE TITLE
gamestream doesnt close. on games. end.

### ISSUE THREAD

**Issue by michielsweb** [dead/moonlight-openelec-rpi2#29]
gamestream stays open til i walk over to my pc to close or alt tab gamestream. 
is there anyway u could add a shortcut. or automatic close down back to moonlight menu or kodi after u close a game?

**Comment by burtaverde** [comment]
same problem here. It just shows me my pc desktop. I usually just close nvidia game stream and was thinking about making something that restarts it automatically when it's closed.
