### ISSUE TITLE
Wanted to give something back; with this you can manage custom resolution on gui

### ISSUE THREAD

**Issue by rapidreporter** [dead/moonlight-openelec-rpi2#3]
Isn't an issue, but didn't know where else I should paste it.

Here are some small changes, that allow you to set a custom resolution:
- file:  /storage/.kodi/addons/script.moonlight/resources/settings.xml

&lt;setting id="MOON_RESOLUTION" type="labelenum" label="Resolution" values="720p|Custom|1080p" default="720p" />
        &lt;setting id="MOON_WIDTH_RESOLUTION" type="text" label="Width" visible="eq(-1,1)" default="1366" />
        &lt;setting id="MOON_HEIGHT_RESOLUTION" type="text" label="Height" visible="eq(-2,1)" default="768" />

...

---
- file: /storage/.kodi/addons/script.moonlight/bin/service.sh
  ...
  
  ```
          if [ "$MOON_RESOLUTION" = "720p" ]; then
                  MOONLIGHT_ARG="$MOONLIGHT_ARG -720"
          elif [ "$MOON_RESOLUTION" = "1080p" ]; then
                  MOONLIGHT_ARG="$MOONLIGHT_ARG -1080"
          else MOONLIGHT_ARG="$MOONLIGHT_ARG -width $MOON_WIDTH_RESOLUTION -height $MOON_HEIGHT_RESOLUTION"
          fi
  ```

...

---
- file: /storage/.kodi/addons/script.moonlight/settings-default.xml

...
   &lt;setting id="MOON_WIDTH_RESOLUTION" value="1366" />
   &lt;setting id="MOON_HEIGHT_RESOLUTION" value="768" />
...

---

Greets ;)

**Comment by dead** [comment]
Thank you!
I'm going to add this.
