### ISSUE TITLE
64bit version

### ISSUE THREAD

**Issue by Ginko-Aloe** [dead/moonlight-openelec-rpi2#30]
Hi there,

I'm running a x64 release of Kodi from Debian. Any chance I can get script.moonlight running from it?

I took a look at the source code but I've not seen any building instruction.

Moonlight-pc works fine but it's a pain in the *ss to have to switch to the Debian desktop to launch it. Doing it from Kodi... wow that looks awesome! :)

**Comment by dead** [comment]
You can try using Libreelec for Generic platform.
