### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Loky31** [dead/moonlight-openelec-rpi2#31]
Hello,

Got a problem when launching a game, it's only goes to black screen...
Controls are working as I'm able to do stuff on source PC, but nothing caming up on PI screen.
I've tried different resolutions/refresh rates...

In log it's waiting for "Waiting for IDR frame" which is likely never received...

I'm using version 1.0.11 as I didn't found the zip for the version 1.1, a link ?

Any help?

**Comment by dead** [comment]
Download the latest release :)

**Comment by Loky31** [comment]
Yeah !!!! THANK YOU SO MUCH!!!

Now remains the weird mapping of my gamesir3 :)
Up is left and so on... I've read something about it somewhere. Just have to find it again :)

I've tried with the dongle, but maybe BT will do the trick better. Let you know then.

**Comment by Loky31** [comment]
Hi,
I did manage to have my GAMESIR3 working by using a key mapper (for emulators) but default mapping for xbox controler is still with error on directions.

Do I need to raise another issue?

**Comment by dead** [comment]
You can try edit the controller mapping via ssh
`moonlight-embedded map xbox360.conf`

**Comment by He4dnut** [comment]
Hey, 
at first: thanks for your work on this!!
I'm running the moonlight addon from the libreelec.tv repo on raspberry pi 3 with libreelec. Everything worked fine but then I got the same issue: Black screen on the TV, but sound and controller is working. The problem appeared since the last Game ready driver update 3 days ago. 
I'm running the game ready driver version 376.33 on GTX 750 Ti and GFE version 3.2.0.96.
Maybe its the same problem like in this thread? https://github.com/moonlight-stream/moonlight-ios/issues/237 
According to the last post there came a new built for iOS 9 hours ago. Any ideas? Thank you in advance!

**Comment by lordhazcuky** [comment]
Hello,
I also can confirm that the latest Geforce Experience (3.2.0.96) screwd up something. 
Black screen with sound and with working controller.
I also has the issue with the weird xbox360 controller mapping but thats a minor issue.

**Comment by flod82** [comment]
Same here. Black Screen, Audio works. Xbox360 Lt and rt wont work 😥

**Comment by mahuika88** [comment]
It looks like this was fixed here: https://github.com/irtimmer/moonlight-embedded/issues/446, there is a new release of moonlight embedded (2.2.3): https://github.com/irtimmer/moonlight-embedded/releases

Would it be possible to get this into a this package?

**Comment by dead** [comment]
I'm going to release a new version soon :)

**Comment by lordhazcuky** [comment]
Thanks for your response and work!

**Comment by rottmanj** [comment]
I am seeing the same issue with 2.2.3 installed and the GFE 3.2.0.96. I have also tried downgrading to ME 2.2.1 but I get the same results.

**Comment by BETEP-ok** [comment]
confirm black screen as well.
latest script package, GeforceExperience 3.2.0.96

feels like those f*****s in Nvidia screwed up something.

Moonlight plugin for chrome works perfectly. So feels like the issue was fixed in the Moonlight itself.

**Comment by cyberjunkie2k** [comment]
Yep. Black screen with audio here on OpenELEC (rpi2). We trouble you a lot, don't we?

**Comment by dead** [comment]
Can someone test this? [script.moonlight-1.0.11.zip](https://github.com/dead/script.moonlight/files/681749/script.moonlight-1.0.11.zip) (Openelec Rpi2)

Thanks

**Comment by cyberjunkie2k** [comment]
Worked for me! I haven't tried it thoroughly but video and audio are working A-OK. Thanks again!

**Comment by BETEP-ok** [comment]
tested - works like a charm )

thnx

**Comment by lordhazcuky** [comment]
I'm happy to say that the audio and video is working perfectly, only the controller mapping is effed up, but thats maybe something on my part.

Thanks for your help dead!

**Comment by californicat** [comment]
@dead worked for me as well, could I ask you for xbox one controller support? x360 option doesn't work for me( 
It would be great. Thank you.

**Comment by dead** [comment]
You can use (in ssh) `moonlight map .kodi/addons/script.moonlight/share/moonlight/mappings/xbox360.conf` and create a new mapping file to the xbox one. If you send me the new file I can add it.

**Comment by californicat** [comment]
I assume mapping is not a problem in this case. If I connect xone controller via usb to raspi3, X in the middle is blinking a while. I think the driver is missing. 

Another point: any plan to update your script for OpenELEC Stable Releases (7.0.0) support?

Thank you again!
