### ISSUE TITLE
Failed to pair to server

### ISSUE THREAD

**Issue by tomismrkolj** [dead/moonlight-openelec-rpi2#34]
Hi,

I have moonlight script on kodi 18 alpha.
Cannot pair it with the server.
It says "Failed to pair to server" after correct PIN is enterd on the server side.

RPi2, Libreelec Millhouse build 27.12.2016, server NVIDIA GTX 670, with 376.33 driver and GFE 3.2.0.96

**Comment by phippg** [comment]
Same problem. RPi3, LibreELEC (Krypton) v7.90.010 ALPHA, GTX 660, 376.33 driver, GFE 3.2.0.96

**Comment by phippg** [comment]
There is no log available in `Userdata\addon_data\script.moonlight\service.log`. Manual pairing from the commandline works.

**Comment by tomismrkolj** [comment]
I agree. No log and manual pairing works OK.

tomi

**Comment by Laktosefrei** [comment]
Seems like Moonlight 2.2.2 dosent work with GEP 3.2.0.96
There is a Moonlight Version 2.2.3 out and fixed this issue ... but no clue how to install it on the Raspberry Pi - Openelec without the script
Can the dev make a new one with Moonlight 2.2.3

Would be very nice :)

**Comment by ladismrkolj** [comment]
I wrote an email to the DEV. Let's hope that he answers soon.

And hopfully makes an update:)

ladi

**Comment by phippg** [comment]
@Laktosefrei I did have that problem when I tested Moonlight for the first time (on a Debian system), but it's weird that pairing + starting the stream works from the commandline on LibreELEC. Would suggest a different problem than version incompability, though it might still be that...

**Comment by appletalk** [comment]
Impatient bump of the same issue :smile: 
But really great work on this plugin, just hoping for an update soon.

**Comment by cjvaughter** [comment]
It seems to be a library issue. Pairing with the moonlight binary works fine, but using libgamestream results in this:
```
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    gs = LibGameStream("/storage/.kodi/addons/script.moonlight/lib")
  File "/storage/.kodi/addons/script.moonlight/lib/moonlight.py", line 40, in __init__
    self.commonlib = ctypes.cdll.LoadLibrary(os.path.join(libpath, "libmoonlight-common.so.0"))
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
OSError: /storage/.kodi/addons/script.moonlight/lib/libmoonlight-common.so.0: undefined symbol: EVP_CIPHER_CTX_cleanup
```

Everything else seems to work fine.

As a temporary workaround, you can pair manually and then copy the keys from `~/.cache/moonlight/` to `~/.kodi/userdata/addon_data/script.moonlight/keys/`

**Comment by phippg** [comment]
@cjvaughter That makes sense, I'll test your workaround!

**EDIT:** easy temporary fix, thanks a lot!

**Comment by dead** [comment]
Ops, still looking...

**Comment by ArturKaul** [comment]
i have same problem, but i cant Manual pairing from the commandline too
i get: "moonlight: error while loading shared libraries: libcrypto.so.32:
cannot open shared object file: No such file or directory
-sh: moonlight:: not found"

**Comment by 4noxx** [comment]
same problem with LE on my x64 System

- How can i pair manually?
- Where can i find v 2.2.3? 

regard

**Comment by dead** [comment]
For some weird reason that I was not able to identify, in libreelec the addon is failing to verify the signing in the paring process...

You can pair manually using ssh and running `moonlight pair` , then you will ned to copy the keys from `~/.cache/moonlight/` to `~/.kodi/userdata/addon_data/script.moonlight/keys/`

**Comment by ArturKaul** [comment]
thank you, but i cant pair manually? i get еrror

**Comment by dead** [comment]
What OS are you using? Libreelec, Openelec? Version?

**Comment by ArturKaul** [comment]
Libreelec 7.0.3

**Comment by TwistedBE** [comment]
I'm using Libreelec 8.0.0 (on a RPi3 Slice) and a 980GTX desktop.
When opening Moonlight I always get "pairing failed" even though I'm entering the correct code on the desktop.
When using ssh and the `moonlight pair` command the desktop asks for a code but nowhere does it show witch code I need.

I'm a bit stuck on what to do next to make it work.
Moonlight works perfectly on my android phone so its only a RPi issue.

**Comment by towfiqi** [comment]
> then you will ned to copy the keys from ~/.cache/moonlight/ to ~/.kodi/userdata/addon_data/script.moonlight/keys/

Can anyone please let me know how to do that with ssh?

**Comment by Mcavity5** [comment]
Im having the same issue. cant pair with moonlight on libeelec

**Comment by towfiqi** [comment]
@Mcavity5 This is how I Did it:

1. Install Putty and winSCP on your windows PC.
2. Login to your libreelec through putty with your libreelec's ipaddress and default username: `root` password `libreelec`
3. Then run this command: moonlight pair 192.168.1.xxx
replace the ip address with your host pc's ip address where you want to stream the games from.
4. Upon entering this command you will have to insert the generated key in Nvidia gamestream's password popup field. When you do that, your device will be connected and necessary key files will be generated in your libreelec's cache folder. You can close putty now.
5. Now You will need to copy these key files to your Libreelec Moonlight addon folder. To do that, First open up winSCP and login to your libreelec and then navigate to `storage/.cache/moonlight/` folder and then donwload the 4 key files you find in this folder. Now navigate to `storage/.kodi/userdata/addon_data/script.moonlight/keys/` and upload the 4 files in that folder.
6. That's it. You should be able to access your games without any issues now.

Hope this helps.

**Comment by Mcavity5** [comment]
Thanks! that worked perfectly!

**Comment by towfiqi** [comment]
Glad I could Help! :)

**Comment by Cris--** [comment]
When i try to manual pair in terminal i get this:
`moonlight: error while loading shared libraries: libcrypto.so.32: cannot open shared object file: No such file or direct`

Here some logging info:
https://pastebin.com/gfB5CTgh

Installed:
_moonlight 2.2.3, rpi3 + LibreElec 8.0.2. Nvidia 970GTX Driver 385.12 (GeForce Experience 58.3029.1609.1)_

**Found the fix:** https://github.com/dead/script.moonlight/issues/45
