### ISSUE TITLE
Libreelec/ML70.104 (222) Mapping issue Xbox360 wired

### ISSUE THREAD

**Issue by wmoindrot** [dead/moonlight-openelec-rpi2#37]
Hi, I'm having an issue whereby I cannot seem to alter the mappings on Moonlight in Libreelec to configure to my wired xbox controller which is plugged into my raspberry pi 3.

To get ML working in Libreelec7.0.3 I installed ML from Libreelec repo (giving black screen) then applied fix by ByteRaper: https://forum.libreelec.tv/thread-3079.html with WinSCP (showing hidden files in preferences to find .kodi folder in storage). Basically overwritten files: libmoonlight-common.so; libmoonlight-common.so.0; libmoonlight-common.so.2.2.2

I am finding that by vanilla default, the buttons are not properly mapped (Dpad are wrong directions). Have tried configuring plugin to use the vanilla xbox360 mappings but no change noticed. Run 'moonlight map x.conf' over SSH and copied this into the script.moonlight/share/moonlight/mappings and then adjusted settings.xml to reflect my new conf, and selected this within config screen, but it does not make any difference to the actual mappings. It's almost as if it's receiving the mappings from somewhere else. 

I have also tried the above prior to applying ByteRaper fix (black screen but observing local screen) and same behavior seen.

I noticed that under Openelec7 with ML version 1.0.11, just switching to the vanilla xbox mapping made it work well, and so I copied the contents of the conf, and pasted this into my .conf on Libreelec - but still no change.

In the end I have installed 1.0.11 in Libreelec and this now works with correct mapping and video - so if there are no downsides to this for the moment I will leave as this. So kind of a solution. 

Hope this helps, Will

**Comment by tomismrkolj** [comment]
Hi,

I have xbox360 wireless controller.

after a lot of reading and testing I got the map file which at least works,
D-pad is OK, but didn't test the triggers

so this is my xbox360.conf: 

abs_x = 0
abs_y = 1
abs_z = 10
abs_rx = 3
abs_ry = 4
abs_rz = 9
abs_deadzone = 0
abs_dpad_x = -1
abs_dpad_y = -1
reverse_x = false
reverse_y = true
reverse_rx = false
reverse_ry = true
reverse_dpad_x = false
reverse_dpad_y = false
btn_east = 305
btn_south = 304
btn_north = 308
btn_west = 307
btn_select = 314
btn_start = 315
btn_mode = 316
btn_thumbl = 317
btn_thumbr = 318
btn_tl = 310
btn_tr = 311
btn_tl2 = 312
btn_tr2 = 313
btn_dpad_up = 706
btn_dpad_down = 707
btn_dpad_left = 704
btn_dpad_right = 705

**Comment by dead** [comment]
Since this is an old issue I'm going to close it, if you still need some help feel free to open it again.
