### ISSUE TITLE
Cant get the Add-On to start

### ISSUE THREAD

**Issue by shawn89** [dead/moonlight-openelec-rpi2#4]
Hi there,
I can't start the add-on. I'm using Version 1.0.6. and Im on RPi2 with OpenELEC 5.0.8.

It alwas says "Error - Scirpt Failed! : Moonlight" when I try to start it. I already put the IP of my computer in the configuration but it didn't help. I already tried rebooting the RPi, re-installing and even re-downloading the add-on. I dont know what to do anymore. 

Any ideas? :P

**Comment by dead** [comment]
The addon is for OpenELEC 6.0 (actually the moonlight binaries are compiled to it)
Any reason to not update it?

**Comment by shawn89** [comment]
Well to be honest I didn't know there was OpenELEC 6.0 since 5.0 didn't find this with autoupdate. I updated manually and it works. 

Great Work and thank you very much!

**Comment by dead** [comment]
Thank you!
