### ISSUE TITLE
Moonlight-embedded 2.3.0

### ISSUE THREAD

**Issue by dmnc-net** [dead/moonlight-openelec-rpi2#43]
Hi, Iwan has released the 2.3.0 version of the moonlight-embedded, please can you update your addon (eventually LibreELEC addon too)? Please ...

https://github.com/irtimmer/moonlight-embedded/releases/latest
https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/addons/script/moonlight

@CvH

**Comment by CvH** [comment]
@dmnc-net could you test it ? if so which platform (i could provide some testbuild)

**Comment by MopheusDG** [comment]
Hi, I can test Libreelec 8.0.1 on RPi3 if we get an update to 2.3.0. Previous versions are not working for me as GFE 3.5.0 breaks them... again.

**Comment by CvH** [comment]
@MopheusDG http://cvh.libreelec.tv/addons/8.1/moonlight/RPi2/ (106) but completly untested :) thats just the latest from everything

**Comment by MopheusDG** [comment]
@CvH no luck. I updated to 106 using your repo but still can't pair.

**Comment by CvH** [comment]
@MopheusDG if you done it correct then there is noting i can do and we need to wait till https://github.com/irtimmer/moonlight-embedded gets updated/fixed

**Comment by MopheusDG** [comment]
I've been using https://github.com/irtimmer/moonlight-embedded without problems in RPi3 latest linux release. So I think there's nothing to fix from their side, it's just for some reason the LE plugin not working, the main embedded works fine in version 2.3.0. Any idea what could be the reason ?

**Comment by CvH** [comment]
@MopheusDG no idea, we have no one who could test this at all - maybe some change at moonlight embedded but honestly not much I/we can do.

**Comment by dmnc-net** [comment]
@CvH sorry for the late reply. I'm a bit confused here but I'll try to react. Yes, I can test the addon on WeTek Play 2 - LE 8.0.1 and RPi3 (LE 8.0.1 again).

I'm using v. 2.3.0 https://github.com/irtimmer/moonlight-embedded/releases/tag/v2.3.0 release on the Retropie/Raspbian without problems so I think it is a good time to update this addon to use 2.3.0 instead of 2.2.2 (or 2.2.3) too ... @dead what do you think?

**Comment by dmnc-net** [comment]
@MopheusDG I've got some problems with pairing before so I did it in the cli and copied the keys to the right path probably `/storage/.kodi/userdata/addon_data/script.moonlight/keys/`. Let me know if this helps.

**Comment by CvH** [comment]
@dmnc-net I can't guide you because due missing HW i never saw this addon beside the code ;)
