### ISSUE TITLE
2.2.3 and GFE 3.5.0.76: Waiting for IDR frame

### ISSUE THREAD

**Issue by fjrclean** [dead/moonlight-openelec-rpi2#45]
After manually updating from 2.2.2 (which is the latest in libreelec repository) to 2.2.3, I still get a frozen image of the launched application. Sometimes now the streaming will work for a minute or so, although very jumpy, and then completely freeze. I assume this is still an issue with protocol differences.

After installing the 2.2.3 release from this page via zip, I would get a libcrypto error when launched through ssh. To fix I just ssh'd to libreelec and ran:
```
cd /storage/.kodi/addons/script.moonlight/lib/
ln -s  /usr/lib/libcrypto.so.38 libcrypto.so.32
```

**Comment by dead** [comment]
Since this should not happen in newer versions of Libreelec, I'm going to close this.
