### ISSUE TITLE
USB Sound Card ignored, only HDMI Audio. OpenELEC 6.0.3

### ISSUE THREAD

**Issue by elbolutony** [dead/moonlight-openelec-rpi2#5]
I am experiencing a little problem with the audio, as only output from the HDMI port not from my USB sound card (Encore ENMAB-8CM, chip C-Media CM6206).
This prevents me to use the Surround Sound option.
The USB sound card is configured in OpenELEC and works fine with movies.
I apologize for the English, but it's not my native language.
Thank you very much, and excellent job with the AddOn.

PS: I've Installed Hyperion ("Open Source Ambilight") and works flawlessly with Moonlight.

**Comment by dead** [comment]
I'm not really sure how I could fix that and not affect people that don't use audio in usb.

To fix it you will need to edit:
https://github.com/dead/moonlight-openelec-rpi2/blob/master/script.moonlight/bin/service.sh#L80-L83
(found at /storage/.kodi/addons/script.moonlight/bin)

Repleace snd_bcm2835 with snd-usb-audio (in line 80 and 83).

Since I don't own a usb audio card I'm not sure if this will work...

**Comment by elbolutony** [comment]
Didn't work, but thanks for the help. i'm not complaining, you did a wonderful work with the addon.

**Comment by dead** [comment]
No problem, just trying to help :)
Not sure if this is a problem with the addon or the moonlight-embedded...
I think the problem could be the raspberry not detecting the usb as the "default", only the hdmi...
If somehow you find a solution, please post here...

**Comment by dead** [comment]
Hey! Please look at https://github.com/dead/moonlight-openelec-rpi2/issues/6#issuecomment-192888433
Maybe that can help you.
And download the newest release to be able to edit the output audio device!

**Comment by elbolutony** [comment]
It worked, i'm getting a delay in the audio, i'm going to take a look at it. 
Thanks

**Comment by elbolutony** [comment]
It's the "Stream 5.1 surround sound (requires GFE 2.7)" Option. Deactivating it, i get no delay at all.
Will update.

**Comment by elbolutony** [comment]
Little update.  Got it, sorta. 
The delay was caused by the sample rate. Setted manually & fixed to 44,1khz in OpenELEC.
Now i get all the channels mixed up, but only in Moonlight, fine on movies.

**Comment by elbolutony** [comment]
The Rear Left & Right channels are mixed with Front Center & LFE/Subwoofer channels. 
The delay only shows when playing anything other than 5.1. 
Resampling = Delay
(If you want me to stop, please tell, i'm only sharing my experience)
Thanks.

**Comment by elbolutony** [comment]
Got it working. Forget what i said about the sample rate. This last part was non-related to Moonlight.

i made this asound.conf 

> pcm.sound-remap {
>         type route
>         slave {
>                 pcm "dmixer"
>         }
>         ttable.0.0 1
>         ttable.1.1 1
>         ttable.2.4 1
>         ttable.3.5 1
>         ttable.4.2 1
>         ttable.5.3 1
> }
> 
> pcm.dmixer     {
>   type dmix
>   ipc_key 1024
>   slave {
>       channels 6
>       pcm "hw:1,0"
>       period_time 0
>       period_size 1024
>       buffer_size 4096
>       rate 48000
>   }
> 
> }
> 
> pcm.!default {
>         type plug
>         slave.pcm "sound-remap"
> }

and selected "sound-remap" as an output device in Moonlight.

Thanks.

**Comment by elbolutony** [comment]
oooopppssss

**Comment by dead** [comment]
Nice :smile:
