### ISSUE TITLE
LibreElec 8.2.0 on x64 Intel NUC partial screen only

### ISSUE THREAD

**Issue by MopheusDG** [dead/moonlight-openelec-rpi2#53]
Hi, I've been trying to get Moonlight to work with my NUC6 on LE 8.2.0 and it works fine but the screen shown is only partial, I mean, I can see my PC but only 3/4 of the screen, and the rest stays black for some reason. I can provide SShot if that helps.

It's like if the PC is 1080p and the NUC6 is showing only 720p of those 1080p ?

Tried changing ALL the parameters with no luck.

Also, is it possible to activate HEVC (h265) with this plugin ? Cause I only see HW Acceleration but not sure what that means compared to the command line moonlight on Linux.

Thanks.

**Comment by danofun** [comment]
I believe this is an issue with your screen changing resolution and not an issue with this addon. I solved a similar issue on a generic LibreELEC build by running xrandr at a command prompt to determine my display device and forcing a resolution with autostart.sh

/storage/.config/autostart.sh
```
#!/bin/sh
xrandr --output HDMI-0 --mode 1920x1080 --rate 60.00
```
