### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Mulfarion** [dead/moonlight-openelec-rpi2#55]
I use Openelec 7.0.1 and moonlight 1.0.11. I connect to my library on PC, but when I start game on PC do noting and openelec restart. In log file have one line is "Illegal instruction (core dumped)". In what problem? And can I fix it?

P.S. Sorry for my English. :)

**Comment by dead** [comment]
If you still want support for Openelec, let me know.
Closing this issue for now...
