### ISSUE TITLE
Random display breaks in game

### ISSUE THREAD

**Issue by Sph1re** [dead/moonlight-openelec-rpi2#56]
Hello and thank you for your work! 
I have better result with moonlight than steam link ;)

I encounter random display breaks in game (very short, 1 second)

do you have a track?

my config: LibreELEC (Krypton) 8.2.2 on raspberry pi 3
stream host: GFE Version: 3.11.0.73

**Comment by dead** [comment]
You should try changing the bitrate and resolution in the settings
