### ISSUE TITLE
moonlight service file not installed on Libreelec 9 with Kodi 18 Alpha

### ISSUE THREAD

**Issue by unimatrix099** [dead/moonlight-openelec-rpi2#58]
When installing the plugin on Kodi 18 Alpha the service from system.d was not installed on the system, so clicking on any game on the list does nothing. I had to manually copy the .service file to the system. Any idea on how the plugin is installed? Maybe the install logic from Kodi 18 Alpha is broken.. any idea on how this works? If in the plugin directory there is a system.d then the files are copied when installed or?  I couldn't find any tutorials/info on how to setup a plugin with a linux .service file...

**Comment by deanrparry** [comment]
Where do you copy this file to? My install seems to contain it in root storage .kodi add-on resources if memory serves

**Comment by dead** [comment]
https://github.com/dead/LibreELEC.tv/commit/203f5d84bf2b702cd202091d3207f79e1de74e04
Compile this version and you should be able to run the script 😄

**Comment by deanrparry** [comment]
I won't be compiling anything :) I'll wait until someone else does thank you

**Comment by CvH** [comment]
@dead sorry for delay but 40°C fever got me
tested it at my vm and `/storage/.config/system.d/service.moonlight.service` get created but links to `/dev/null` instead to the `moonlight.sh`, it looks like this only works if it is `service.moonlight` instead of `script.moonlight` (that raises the question if this worked at all in the past?)
Do we need to run this as "service" at the background all the time (no idea how this works)?

@deanrparry I uploaded new versions here http://cvh.libreelec.tv/addons/9.0/moonlight/ pls try

**Comment by dead** [comment]
@CvH 
Changing the [xbmc.service.pluginsource.xml](https://github.com/dead/LibreELEC.tv/commit/203f5d84bf2b702cd202091d3207f79e1de74e04#diff-0e1aeb576e7ad2ddd9c600789d7544a2 ) fixed the service problem in LE 9.0, did you tried this?

**Comment by CvH** [comment]
> fixed the service problem in LE 9.0

it creates the `/storage/.config/system.d/service.moonlight.service` file after that change but that file is broken as it links to `/dev/null` instead to the start script - like written a comment above

Currently we are not too sure if maybe only `service.abc` addons are working there at all (we use it for nothing else - besides moonlight). But this shouldn't (I guess) be a new problem.

**Comment by dead** [comment]
I think https://github.com/LibreELEC/LibreELEC.tv/commit/89e6d75a409445cc6c3240ea31191317ecf06f8e  caused the issue. But I tested the xbmc.service.pluginsource.xml change with my latest commit (PKG_VERSION="29f4511") in this repo and it worked.
Btw how do you run libreelec in a vm, vmware, qemu?

**Comment by CvH** [comment]
>I think LibreELEC/LibreELEC.tv@89e6d75 caused the issue

damn it I always forgot about that ;) yea that is very likely - but that it worked before is likely just an accident as it was always the intention of that change to just allow `service.abc`

I updated the Pull with the "latest" that I used https://github.com/LibreELEC/LibreELEC.tv/pull/2629
that creates for me a broken service file 
```
LibreELEC:~/.config/system.d # ls -la
lrwxrwxrwx    1 root     root             9 Mar 30 22:30 service.moonlight.service -> /dev/null
```

a solution from my POV is to rename `script.moonlight` -> `service.moonlight`

**Comment by CvH** [comment]
> Btw how do you run libreelec in a vm, vmware, qemu?

we support VMWarePlayer/Workstation - Player is free (qemu might work too - no idea) 
1. dl https://libreelec.wiki/mirrors ->  LibreELEC-Generic.x86_64-8.2.x.ova
2. import into VMWare, resize hdd, boot
3. done

you can now up/downgrade with every normal LE Generic version (Milhousebuilds etc) ...

**Comment by deanrparry** [comment]
Is a newer version of the addon now available that includes the compiled changes from the dev to work on LE9 x86?

**Comment by CvH** [comment]
still http://cvh.libreelec.tv/addons/9.0/moonlight/
I figured out that there is somewhere an problem that no correct systemd service file is created - no time yet to dig into it (looks like no big thing, it should work)

**Comment by deanrparry** [comment]
Tried that one still fails on x86

**Comment by unimatrix099** [comment]
I made time and build a new version for Rspi3 with the service fix and moonlight fixes (the dead/LibreELEC.tv@203f5d8 modifications, also the sha256 should be changed, now it's not the proper hash for the package) But for me it didn't worked, I still had to copy the service manually  "cp /storage/.kodi/addons/script.moonlight/system.d/script.moonlight.service /storage/.config/system.d/" and enable the service "systemctl enable script.moonlight" + reboot. Also I found that on the first install it will not work, I mean when entering the pair mode/start the plugin, it will fail with an error, until the system is rebooted, after that paring works. The error from the logs is: 
"08:52:58.485 T:3803259776  NOTICE: ADDON: xbmc.addon v17.9.702 installed
08:52:58.485 T:3803259776  NOTICE: ADDON: skin.estuary v2.0.8 installed
08:53:13.553 T:3704603520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: /usr/lib/kodi/kodi.bin: undefined symbol: gs_discover_server
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 78, in <module>
                                                index()
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 29, in index
                                                address = gs.discover_server()
                                              File "/storage/.kodi/addons/script.moonlight/lib/moonlight.py", line 66, in discover_server
                                                self.gslib.gs_discover_server(addr)
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
                                            AttributeError: /usr/lib/kodi/kodi.bin: undefined symbol: gs_discover_server
                                            -->End of Python script error report<--
08:53:13.626 T:4094574608   ERROR: GetDirectory - Error getting plugin://script.moonlight/
08:53:13.626 T:4094574608   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.moonlight/) failed
08:53:28.818 T:3696210816   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)"

This is from the Libreelec master + the fix, so with Kodi Alpha 18 and everything else on the edge.. 

@dead should I create an issue for this?

**Comment by deanrparry** [comment]
I've thrown a hdmi cable across now so moonlight is off my main box thanks anyway guys looks like it's a nightmare scenario :)
