### ISSUE TITLE
Program crash when launching a game

### ISSUE THREAD

**Issue by asonnema** [dead/moonlight-openelec-rpi2#6]
When I select a game to start, the program crash and kodi restart to main menu.
Do I require dependencies?

I'm using openelec 6.03 on rpi2. and moonlight-openelec-rpi2 1.06
Moonlight is working on my IOS device, so the system is capable of streaming.

**Comment by dead** [comment]
No, it don't have any dependencies...
Please post the log file.
It can be found in: `Userdata\addon_data\script.moonlight\service.log`

**Comment by asonnema** [comment]
Here is the log file:

stream -packetsize 1024 -bitrate 10000 -720 -30fps -forcehw -mapping "/storage/.kodi/addons/script.moonlight/bin/mappings/default.conf" -app "Hearthstone: Heroes of Warcraft" -keydir "/storage/.kodi/userdata/addon_data/script.moonlight/keys"
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...Moonlight Embedded 2.1.4 (EMBEDDED;PI)
Connect to 192.168.59.9...
Stream 1280 x 720, 30 fps, 10000 kbps
Alsa error code -2

**Comment by dead** [comment]
Hm... That's odd...
Seems it is a problem with the audio driver or something like that...
Are you using hdmi for video and audio?

Can you provide me more info?
`uname -a`
`lsmod`

**Comment by asonnema** [comment]
I use hdmi for both audio and video.

uname -a:
Linux AMBILIGHT 4.1.18 #1 SMP Mon Feb 29 20:48:22 CET 2016 armv7l GNU/Linux

lsmod:
Module                  Size  Used by
ftdi_sio               29989  1
usbserial              19251  3 ftdi_sio
usbtv                   9440  0
videobuf2_vmalloc       4215  1 usbtv
videobuf2_memops        1270  1 videobuf2_vmalloc
videobuf2_core         31837  1 usbtv
v4l2_common             3213  2 usbtv,videobuf2_core
videodev              100079  3 usbtv,v4l2_common,videobuf2_core
snd_pcm                61495  1 usbtv
snd_timer              17240  1 snd_pcm
snd                    39984  3 usbtv,snd_timer,snd_pcm
bcm2835_gpiomem         2588  0
bcm2708_rng              821  0

**Comment by asonnema** [comment]
Btw, I do have a USB videograbber and an ardiuno usb micro connected to pi2 for ambilight purpuse.

**Comment by dead** [comment]
Try initialize from the ssh and post the output here:

`systemctl stop kodi`
`modprobe snd_bcm2835`
`moonlight -720 -30fps -forcehw -mapping "/storage/.kodi/addons/script.moonlight/bin/mappings/default.conf" -keydir "/storage/.kodi/userdata/addon_data/script.moonlight/keys"`

**Comment by asonnema** [comment]
Still the same error, but i got it to work to find the proper audio device using aplay -l

```
systemctl stop kodi
modprobe snd_bcm2835
aplay -l
```

---

> ***\* List of PLAYBACK Hardware Devices ****
> card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
>   Subdevices: 8/8
>   Subdevice #0: subdevice #0
>   Subdevice #1: subdevice #1
>   Subdevice #2: subdevice #2
>   Subdevice #3: subdevice #3
>   Subdevice #4: subdevice #4
>   Subdevice #5: subdevice #5
>   Subdevice #6: subdevice #6
>   Subdevice #7: subdevice #7
> card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0

---

The hdmi is on 1, so i started the program with the -audio hw:1,0 parameter as following:

```
systemctl stop kodi
modprobe snd_bcm2835
moonlight stream -packetsize 1024 -bitrate 10000 -720 -30fps -mapping "/storage/.kodi/addons/script.moonlight/bin/mappings/default.conf" -app "Hearthstone: Heroes of Warcraft" -keydir "/storage/.kodi/userdata/addon_data/script.moonlight/keys" -audio hw:1,0

```

Is it possible the i can configure the audio parameter in the setting config?

**Comment by dead** [comment]
With the `-audio hw:1,0`, it worked?

There is not this option in the addon...
But now I will have to add it... No ideia how to make it easy or simple...

**Comment by asonnema** [comment]
yes with -audio hw:1,0 it works.

Simple option would be for people who know how to use ssh and use aplay -l would be a settings options for audio input where you can put in manually hw:1,0 

Easy option would be to read out the aplay -l output and give the user the option to choose which audio device you want to use and convert that into the proper audio parameter.

**Comment by dead** [comment]
I will go with the simple option :smile: 
Testing it now, soon I will release a new version.
Thank you!

**Comment by asonnema** [comment]
1.07 is working.
Thanks! I really like the addon.

Btw one side note, when I download as zip file from github,
The zip file is not recognized in kodi, due to the folder sturcture.
moonlight-openelec-rpi2-master\script.moonlight\
When I unzip it and zip only the folder script.moonlight  then kodi recognize it.
folder structure look like: \script.moonlight\
I guess this has to do with the folder structure on github.

Anyways keep up the good work!

**Comment by dead** [comment]
You should download the releases from https://github.com/dead/moonlight-openelec-rpi2/releases
And use the "script.moonlight.zip" not the "Source code (zip)"

Thanks :smile:

**Comment by asonnema** [comment]
Ah :)

**Comment by rapidreporter** [comment]
Thank you. Bought this -
http://www.amazon.de/gp/switch-language/product/B00QIFLKL4/ref=cs_switchlang?ie=UTF8&language=en_GB 
- usb-audio-card for less then 3 € after reading this and the other usb-card themes. Works like a charm with version 1.0.10.
  Now moonlight runs on my video projektor from time to time :) :+1: 

(Because the stupid video projektor has no audio out and the native analog audio is realy worse)

Have a nice day :)
