### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by CvH** [dead/moonlight-openelec-rpi2#60]
The script looks not working anymore even if moonlight works from ssh.
You get some errors at the log https://pastebin.com/4mkdDJk6
`WARNING: Attempt to use invalid handle -1`

additional you need likely https://github.com/CvH/script.moonlight/commit/59dbc2d2edc7effff05e567dd3e724248b7bebf2 to make it work. Btw this is not really a proper fix (from my POV), the script should check for `.so.*` instead for a hard coded version (I guess).

logs are from https://github.com/LibreELEC/LibreELEC.tv/pull/2616

**Comment by dead** [comment]
After fixing the `.so.3` is the pairing via kodi working?

**Comment by CvH** [comment]
no, it is still just working via ssh
but at least the addon itself shows something instead to instantly crash (after changing to `.so.3`)
log shows something about `WARNING: Attempt to use invalid handle -1`
I guess through 
`DEBUG: RunScriptWithParams - calling plugin Moonlight('plugin://script.moonlight/','-1','?app=Star+Wars+Battlefront&mode=stream','resume:false')`

I have no hw to test this, all I can do is c/p logs from other users ;)

**Comment by deanrparry** [comment]
As soon as we have a compiled version of a generic build I can test for you and report back

**Comment by deanrparry** [comment]
.so.3 when not I manually edit the py myself has no change... Game list but no progress and yes pairing still works
