### ISSUE TITLE
Openelec support?

### ISSUE THREAD

**Issue by dead** [dead/moonlight-openelec-rpi2#61]
Since Libreelec supports this addon by default, I was thinking in dropping the Openelec support.
Does anyone still want this addon to support Openelec?

**Comment by pcinhaber** [comment]
Hi,

is there any chance to get a compatible moonlight Addon for Openelec 8 with Kodi 17.3?

Thank you and kind regards

**Comment by Metalor696** [comment]
Yes please!!

**Comment by Nitrus** [comment]
Hi, I'm assuming OpenElec support was dropped?
Is there a build that works with OpenELEC 8?
