### ISSUE TITLE
Where is this in LibreELEC 9.0.1?

### ISSUE THREAD

**Issue by rabejens** [dead/moonlight-openelec-rpi2#64]
I searched the whole LibreELEC repository but can't find it. Is there a way to install it manually?

**Comment by dead** [comment]
LibreELEC dropped the support for this plugin (because I was unable to maintain it).
I will try to update it later and release a zip.

**Comment by dead** [comment]
https://github.com/dead/script.moonlight/issues/65#issuecomment-512966596
