### ISSUE TITLE
Xbox 360 Controller Mapping

### ISSUE THREAD

**Issue by elbolutony** [dead/moonlight-openelec-rpi2#7]
I've found that the triggers doesn't work. 
Replacing the next lines in moonlight-openelec-rpi2/script.moonlight/bin/mappings/xbox360.conf 
(Lines 1 to 6)

> abs_x = 0
> abs_y = 1
> abs_z = **10**
> abs_rx = 3
> abs_ry = 4
> abs_rz = **9**

with: 
(Lines 1 to 6)

> abs_x = 0
> abs_y = 1
> abs_z = **2**
> abs_rx = 3
> abs_ry = 4
> abs_rz = **5**

Make both triggers work, tested in Mass Effect 2, Mass Effect 3, Borderlands 2, NFS: Most Wanted, Crysis 1 and Crysis 2.

[xbox360.conf MODIFIED.zip](https://github.com/dead/moonlight-openelec-rpi2/files/160535/xbox360.conf.MODIFIED.zip)

**Comment by dead** [comment]
Thank you :smile:
