### ISSUE TITLE
Can't play with Dualshock 3

### ISSUE THREAD

**Issue by caiomatrix** [dead/moonlight-openelec-rpi2#8]
I'm having trouble using Dualshock 3 and Moonlight. Everything works great with the Xbox 360 controller (with moddified conf file from the other issue here) but I can't even get the game to start with the Dualshock 3 plugged with a USB cable. 

This is the log:
`stream -packetsize 1024 -bitrate 10000 -720 -60fps -forcehw -surround -mapping "/storage/.kodi/addons/script.moonlight/bin/mappings/dualschock3.conf" -app "Rocket League" -keydir "/storage/.kodi/userdata/addon_data/script.moonlight/keys"
Unable to open custom mapping file: /storage/.kodi/addons/script.moonlight/bin/mappings/dualschock3.conf
Moonlight Embedded 2.1.4 (EMBEDDED;PI)`

**Comment by dead** [comment]
Ops, there is a typo in settings.xml
Please change dualschock3 to dualshock3 in https://github.com/dead/moonlight-openelec-rpi2/blob/master/script.moonlight/resources/settings.xml#L16

Going to fix it in the next release.

**Comment by caiomatrix** [comment]
Yay! Issue resolved! :+1:
