### ISSUE TITLE
Fails to start - Openelec 7

### ISSUE THREAD

**Issue by squidrpi** [dead/moonlight-openelec-rpi2#9]
I get the following error when try to start it from Kodi (Jarvis) using Openelec 7 on an RPi3

```
18:05:35 T:1464185760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>                   
                                            Error Contents: libssl.so.32: cannot open shared object file: No such file or directory   
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 78, in <module>
                                                index()
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 25, in index
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")
                                              File "/storage/.kodi/addons/script.moonlight/resources/moonlight.py", line 35, in __init
                                                self.gslib = ctypes.cdll.LoadLibrary(os.path.join(libpath, "libgamestream.so.0"))
                                              File "/home/oe/OE7/build.OpenELEC-RPi2.arm-7.0.0/Python-2.7.11/.install_pkg/usr/lib/pyth
                                              File "/home/oe/OE7/build.OpenELEC-RPi2.arm-7.0.0/Python-2.7.11/.install_pkg/usr/lib/pyth
                                            OSError: libssl.so.32: cannot open shared object file: No such file or directory       
                                            -->End of Python script error report<--                                                   
18:05:35 T:1963081728   ERROR: GetDirectory - Error getting plugin://script.moonlight/
18:05:35 T:1963081728   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.moonlight/) failed
```

I have no service.log file, errors only appear in kodi.log

**Comment by dead** [comment]
Any particular reason to use Openelec 7?
The addon is for Openelec 6.

**Comment by dead** [comment]
Try putting this on /storage/.kodi/script.moonlight/lib folder
[libssl.so.32.zip](https://github.com/dead/moonlight-openelec-rpi2/files/177032/libssl.so.32.zip)

**Comment by squidrpi** [comment]
Still missing a library, here's the ldd on moonlight:
        linux-vdso.so.1 (0x7ef64000)
        /lib/libarmmem-a7.so (0x76f3a000)
        libgamestream.so.0 => /storage/.kodi/addons/script.moonlight/lib/libgamestream.so.0 (0x76f16000)
        libasound.so.2 => /usr/lib/libasound.so.2 (0x76e79000)
        libopus.so.0 => /storage/.kodi/addons/script.moonlight/lib/libopus.so.0 (0x76e28000)
        libudev.so.1 => /lib/libudev.so.1 (0x76e0d000)
        libdl.so.2 => /lib/libdl.so.2 (0x76dfa000)
        libmoonlight-common.so.0 => /storage/.kodi/addons/script.moonlight/lib/libmoonlight-common.so.0 (0x76dd5000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x76d91000)
        libssl.so.32 => /storage/.kodi/addons/script.moonlight/lib/libssl.so.32 (0x76d47000)
        libcrypto.so.32 => not found
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x76d2c000)
        libavahi-common.so.3 => /usr/lib/libavahi-common.so.3 (0x76f6e000)
        libavahi-client.so.3 => /usr/lib/libavahi-client.so.3 (0x76d1e000)
        libuuid.so.1 => /lib/libuuid.so.1 (0x76d1a000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x76cf2000)
        libc.so.6 => /lib/libc.so.6 (0x76bbe000)
        /lib/ld-linux-armhf.so.3 (0x76f4d000)
        libcrypto.so.32 => not found
        libm.so.6 => /lib/libm.so.6 (0x76b40000)
        librt.so.1 => /lib/librt.so.1 (0x76b29000)
        libresolv.so.2 => /lib/libresolv.so.2 (0x76b05000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x76ad9000)
        libssl.so.35 => /usr/lib/libssl.so.35 (0x76a91000)
        libcrypto.so.35 => /usr/lib/libcrypto.so.35 (0x76941000)
        libz.so.1 => /usr/lib/libz.so.1 (0x76930000)
        librtmp.so.1 => /usr/lib/librtmp.so.1 (0x7691a000)
        libcrypto.so.32 => not found
        libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x768e1000)
        libsystemd.so.0 => /lib/libsystemd.so.0 (0x76875000)

Fair enough if it doesn't work on Openelec 7 - I know it's not out yet!

**Comment by dead** [comment]
Well this is the last missing: [libcrypto.so.32.zip](https://github.com/dead/moonlight-openelec-rpi2/files/178992/libcrypto.so.32.zip)

I'm going to compile against openelec 7 when released.

**Comment by squidrpi** [comment]
Works great now thanks!

**Comment by ISO-B** [comment]
Any change to get this complied against Openelec 7? It's now released
